Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [36]:
import numpy as np
def gen_van_matrix(inp_vector, n, increasing = False):
    if increasing == False :
        return np.array([x**(n-i-1) for x in inp_vector for i in range(n)]).reshape(inp_vector.size,n)
    else :
        return np.array ([x**i for x in inp_vector for i in range(n)]).reshape(inp_vector.size,n)
inp_vector=np.array([1,2,3,4])
n=3
print(gen_van_matrix(inp_vector, n, increasing = False))
print(gen_van_matrix(inp_vector, n, increasing = True))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

In [38]:
n=10
k=4
values=[10,20,30,40,50,60,70,80,90,100]
sum=0
i=3
for value in values:
    sum = values[i-3]+values[i-2]+values[i-1]+values[i]
    
    if values.index(value)==i:
        
        i+=1
        print(sum/4)                                                               

25.0
35.0
45.0
55.0
65.0
75.0
85.0


# Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [41]:
values = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
i = 2
def moving_avg(values,i):
    for value in values:
        sum = values[i-2]+values[i-1]+values[i]
        if values.index(value)==i:
            i+=1
            print(sum/3)
moving_avg(values,i)


5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
